# Generated by Django 4.1.5 on 2023-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='issue',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
