# Generated by Django 4.1.5 on 2023-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_home_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume_title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
