# Generated by Django 4.1.5 on 2023-04-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_resume_home_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.IntegerField(default='')),
                ('subject', models.CharField(default='', max_length=25)),
                ('requirement', models.CharField(default='', max_length=1000)),
                ('con_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
